[package]
name = "chatgpt-conversation-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.15"
serde_json = "1.0"
chrono = "0.4"
url = "2.2"
serde = { version = "1.0.216", features = ["derive"] }
